### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by antoine3000** [MR-Addict/Pi-Pico-SSD1306-C-Library#1]
Hello !
Thank you for your library, it seems to be what I was looking for with my project.
I would like to use it within a Platformio project structure but I don't know how to do it. I'm not familiar with C++ architecture.
How do you use it? Thanks!

**Comment by MR-Addict** [comment]
Hi there!

Pi Pico C++ coding is similar to C coding. 

If you want to use this library, you just need to clone this repository, and the final file structure should be like below:

- **build**(build files, including .uf2 file)
- **src**(source code folder)
  - **lib**
    - **OLED**(oled library)
  - **bitmap.h**(for display images)
  - **OLEDDISPLAY.cpp**(main programme)
- **CMakeLists.txt**(for cmake)

You should put your build file into `build` folder after you cmake yourself.

The main programme is OLEDDISPLAY.cpp, sorry for this strange file name.

And you may need to modify some changes in CMakeLists.txt file.

You can contact me if you come across other problems.

Have a nice day!

**Comment by MR-Addict** [comment]
I'm sorry for not understanding your issue well.

I'm not using Platformio, and don't know what's framework you use on Platformio, so I suggest you google it.

As I know Platformio also use cpp for programming, thus you can copy or modify my library in `src/lib/OLED folder`.

Apologize sincerely!
